from __future__ import annotations

FACT_PLAYER_GW_COLS = [
    "season",
    "gw",
    "player_code",
    "team_code",
    "opponent",
    "was_home",
    "minutes",
    "starts",
    "goals",
    "assists",
    "clean_sheets",
    "goals_conceded",
    "saves",
    "yellow",
    "red",
    "bonus",
    "bps",
    "influence",
    "creativity",
    "threat",
    "ict_index",
    "tackles",
    "recoveries",
    "clearances_blocks_interceptions",
    "defensive_contribution",
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements",
    "expected_goals_conceded",
    "total_points",
    "value",
    "value_source",
    "xp",
]

# Live API stats key -> fact column
LIVE_STATS_MAP = {
    "minutes": "minutes",
    "starts": "starts",
    "goals_scored": "goals",
    "assists": "assists",
    "clean_sheets": "clean_sheets",
    "goals_conceded": "goals_conceded",
    "saves": "saves",
    "yellow_cards": "yellow",
    "red_cards": "red",
    "bonus": "bonus",
    "bps": "bps",
    "influence": "influence",
    "creativity": "creativity",
    "threat": "threat",
    "ict_index": "ict_index",
    "tackles": "tackles",
    "recoveries": "recoveries",
    "clearances_blocks_interceptions": "clearances_blocks_interceptions",
    "defensive_contribution": "defensive_contribution",
    "expected_goals": "expected_goals",
    "expected_assists": "expected_assists",
    "expected_goal_involvements": "expected_goal_involvements",
    "expected_goals_conceded": "expected_goals_conceded",
    "total_points": "total_points",
}

SUM_STAT_COLS = [
    "minutes",
    "starts",
    "goals",
    "assists",
    "clean_sheets",
    "goals_conceded",
    "saves",
    "yellow",
    "red",
    "bonus",
    "bps",
    "influence",
    "creativity",
    "threat",
    "ict_index",
    "tackles",
    "recoveries",
    "clearances_blocks_interceptions",
    "defensive_contribution",
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements",
    "expected_goals_conceded",
    "total_points",
]

INT_COLS = [
    "gw",
    "player_code",
    "team_code",
    "opponent",
    "minutes",
    "starts",
    "goals",
    "assists",
    "clean_sheets",
    "goals_conceded",
    "saves",
    "yellow",
    "red",
    "bonus",
    "bps",
    "tackles",
    "recoveries",
    "clearances_blocks_interceptions",
    "defensive_contribution",
    "total_points",
    "value",
]
